# Site
name: "David P. Rush"
title: "David P. Rush"
description: "UNDER CONSTRUCTION: Ventures and thoughts..."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /davidprush.github.io
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sal:
    name: David P. Rush
    display_name: David P. Rush
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: me@davidprush.com
    web: https://www.davidprush.com
    twitter: https://twitter.com/davidprush
    description: "Business owner and technologist. You are currently viewing David P. Rush's site for Rush Solutions LLC, an information technology consultancy."
  john:
    name: David P. Rush
    display_name: David P. Rush
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: me@davidprush.com
    web: https://www.davidprush.com
    twitter: https://twitter.com/davidprush
    description: "Business owner and technologist. You are currently viewing David P. Rush's site for Rush Solutions LLC, an information technology consultancy."
  david:
    name: David P. Rush
    display_name: David P. Rush
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: me@davidprush.com
    web: https://www.davidprush.com
    twitter: https://twitter.com/davidprush
    description: "Business owner and technologist. You are currently viewing David P. Rush's site for Rush Solutions LLC, an information technology consultancy."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "UA-54098633-1"
# adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [.ruby-gemset, .ruby-version, Makefile, changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, vendor/]

