title: David Rush
description: |
  "...success, like happiness, cannot be pursued; it must ensue
  ...as the unintended side-effect of one's personal dedication
  to a course greater than oneself." <br />
  -- Mihaly Csikszentmihalyi
show_downloads: false
google_analytics:
theme: jekyll-theme-time-machine