title: David P. Rush
description: |
  "...success, like happiness, cannot be pursued; it must ensue <br />
  ...as the unintended side-effect of one's personal dedication <br />
  to a course greater than oneself." <br />
  <i>--Mihaly Csikszentmihalyi</i>
show_downloads: true
google_analytics: UA-54098633-1
theme: jekyll-theme-minimal
plugins: 
  - jekyll-feed 
  - jekyll-seo-tag.