### Site info:
title: David Rush
tagline: |
  "...success, like happiness, cannot be pursued; it must ensue
  ...as the unintended side-effect of one's personal dedication
  to a course greater than oneself." <br />
  -- Mihaly Csikszentmihalyi, Flow: The Psychology of Optimal Experience
theme: freshman21
author: David Rush
email: davidprush@gmail.com
description: "David Rush is a Jekyll blog theme." # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "David Rush, blogs, stuff"
baseurl: "/davidprush # the subpath of your site, e.g. /blog/
url: "https://davidprush.com" # the base hostname & protocol for your site
locale: en_US

### Personal info and site tools info:
twitter_username: davidprush
github_username:  davidprush
disqus_shortname: 
favicon:     "/images/favicon.ico"
aboutme: Hi, I am David Rush. # these are shown on aboutme-sidebar.
aboutme_photo: images/thumbnail.png.
google_analytics_key: 

### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English (en), Chinese (cn), Japanese (jp), Polish (pl), Korean (kr),  Russian (ru), Turkish (tr), and Indonesian (id).

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "
      Google_search: "Site Search"
      Home: "Home"
      About: "About"
      Guestbook: "Guestbook"
      Subscribe: "Subscribe"
      
### your Blogroll info, only name can shown on the page.

Blogroll:
      - name: Freshman
        href: http://yulijia.net/freshman
        title: Another Jekyll blog theme
      - name: author's website
        href: http://yulijia.net/
        title: Lijia Yu's website


### Build settings
markdown: kramdown
#highlighter: pygments
kramdown:
        input: GFM
        syntax_highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5
excerpt_separator: <!-- more -->
