title: David P. Rush
description: |
![Branching](/assets/images/banner-img.png)
  <br />
  <i>Principal Owner</i>
show_downloads: true
google_analytics: UA-54098633-1
theme: jekyll-theme-minimal
plugins: 
  - jekyll-feed 
  - jekyll-seo-tag.
