title: David P. Rush
description: <img src="/assets/images/Rush-Solutions-LLC-Logo.png" width="200" height="200"/>
show_downloads: false
google_analytics: UA-54098633-1
theme: jekyll-theme-minimal
plugins: 
  - jekyll-feed 
  - jekyll-seo-tag.
