title: David P. Rush
description: |
  "...success, like happiness, cannot be pursued; it must ensue <br />
  ...as the unintended side-effect of one's personal dedication
  to a course greater than oneself." <br /> <br /> 
  _--Mihaly Csikszentmihalyi_<br /> 
show_downloads: true
google_analytics: UA-54098633-1
theme: jekyll-theme-midnight
plugins: 
  - jekyll-feed 
  - jekyll-seo-tag.