title: David P. Rush
description: <img src="/assets/images/thumbnail.png" width="100" height="100"/>
show_downloads: true
google_analytics: UA-54098633-1
theme: jekyll-theme-minimal
plugins: 
  - jekyll-feed 
  - jekyll-seo-tag.
